
// 内页

Stanford Kant Lectures
The Stanford Kant Lectures are an invited series sponsored by the Stanford
University department of philosophy. Philosophers are invited to reflect on
the state of the art in their field and to report on current research in a way that
is accessible to the broader community of scholars, educators, students and
the public at large. Topics range from Kant's philosophy of science to the
nature of human desire. The Kant Lecturer is selected by the department in
light of its judgment that the speaker has a deep understanding ofthe issues in
his or her field, and a vision of their connection to questions of lasting concern across academic disciplines.

// 内页
MICHAEL FRIEDMAN
Dynamics ofReason
The 1999 Kant Lectures at Stanford University

CSLI Publications
Center for the Study of
Language and Information
Stanford, California

// 图书信息
Library of Congress Cataloging-in-Publication Data
Friedman, Michael, 1947-
Dynamics of reason / Michael Friedman.
p. cm.
(Stanford Kant Lectures)
Includes bibliographical references and index.
ISBN 1-57586-291-3 (alk. paper)-ISBN 1-57586-292-1 (pbk.: alk. paper)
1. Science-Philosophy. I. Title
Q175 .F892 2001
501-dc21
2001017171

// 纪念
in memory of
Carl Gustav ("Peter") Hempel
teacher, mentor, friend

// 引言
It might be supposed that [reason’s demand for systematic unity and simplicity] is merely an economical contrivance whereby reason seeks to save itself all possible trouble, a hypothetical attempt, which, if it succeeds, will, through the unity thus attained, impart probability to the presumed principle of explanation. But such a selfish purpose can very easily be distinguished from the Idea. For in conformity with the Idea everyone presupposes that this unity of reason accords with nature itself, and that reason - although indeed unable to determine the limits of this unity - does not here beg but command.

// 目录
Contents
Preface xi
Part One: The Lectures
I. The Idea of a Scientific Philosophy 3
II. Historical Perspectives on the Stratification of Knowledge 25
III. Rationality, Revolution, and the Community of Inquiry 47
Part Two: Fruits of Discussion
1. The Relativized A Priori 71
2. A Priori Principles and Empirical Evidence 83
3. Rationality and Revolution 93
4. The Role of Philosophy 105
5. Other Problems, Other Sciences 117
References 131
Index 137

// 前言
= Preface

For the past twenty years I have been pursuing historical studies on the relationship between developments in scientific philosophy from Kant (in the late eighteenth century) to logical empiricism (in the early twentieth) and concurrent developments taking place within the sciences, principally within the exact sciences of logic, mathematics, and mathematical physics. These studies concentrated on Kant's involvement with the sciences of his time (Euclidean geometry and Newtonian physics, for example) and the various ways in which late nineteenth and early twentieth century revolutionary changes within these sciences (non-Euclidean geometry and relativistic physics, for example) motivated early twentieth century logical empiricists to undertake similarly revolutionary changes in the Kantian and neo-Kantian philosophy oftheir time. My primary aim was to depict the deep and intricate connections between the historical development of scientific philosophy, on the one hand, and the parallel evolution of the exact sciences themselves, on the other.

I did not, however, attempt to draw substantive morals for our contemporary philosophical predicament from these historical studies. Indeed, my dominant tone was rather unhopeful. Kant's original philosophical synthesis had failed due to unforeseen revolutionary changes within the sciences, and the logical empiricists's radical revision of this synthesis had also failed to do
justice to the very rapid changes taking place within early twentieth century science. In response to this situation I offered only the indeterminate suggestion that we, too, should attempt a fruitful interaction between contemporary philosophical practice and developments within the sciences themselves, and the pessimistic conclusion that we now have no idea how to go about this
given the twin failures of Kantianism and logical empiricism.

In the mid to late 1990s I began to see a way out ofthis dilemma. It was not yet clear how one could preserve any kind of commitment to a Kantian or neo-Kantian conception of a priori principles in the exact sciences (as in Kant's original conception of the synthetic a priori, for example, or Rudolf Carnap's version of the analytic a priori developed in the logical empiricist
tradition), but I was convinced, at the same time, that the dominant viewpoint within contemporary scientific philosophy – some or another version of naturalistic epistemological holism – is entirely incapable of providing an adequate philosophical perspective on these sciences. The idea I then came up with, against this twofold background, was that one could attempt to combine basic aspects of Carnap's philosophy of formal languages or linguistic frameworks with fundamental features of Thomas Kuhn's much less formal theory of scientific revolutions. And in this way, more specifically, one could articulate a conception of dynamical or relativized a priori principles within an historical account of the conceptual evolution of the sciences rather than a purely syntactic or semantic account of the formal language(s) of the sciences. One could thus reap the benefits of Kuhnian conceptual history while simultaneously avoiding the drawbacks of Carnapian formal Wissenschaftslogik. In particular, W. V. Quine's well-known and widely accepted attack on the Carnapian conception of analytic truth need no longer compel us to adopt a thoroughgoing epistemological holism according to which there is nothing left of the a priori at all.

In 1997 I had the opportunity to deliver the Whitehead Lecture at Harvard University and the Presidential Address to the Central Division of the American Philosophical Association. I chose, for both occasions, the topic of "Philosophical Naturalism" [Friedman (1997a)], where my aim, in particular, was to attack the contemporary consensus in favor of Quinean epistemological holism on behalf of a neo-Kantian (and historicized) conception of relativized a priori principles. I found, at the same time, that I was thereby able to develop a new positive conception of the peculiar role of scientific philosophy vis-a.-vis the sciences, as a distinctive meta-scientific level of thought or discourse making its own indispensable contribution to the rationality of radical conceptual revolutions (Kuhnian "paradigm-shifts") taking place within the sciences themselves. I further developed these ideas in a second paper, "On the Idea of a Scientific Philosophy:' which I then delivered as part of a series on "Science and Defining the Human" at Northwestern University, as the Stice Lecture at the University of Washington, as a Distinguished Visitor at the University of California at Riverside, as the Jacobson Lecture at the University of London, the Hall Lecture at the University of Iowa, and the Werkmeister Lecture at Florida State University.

This last paper then became the first lecture in the three-lecture series that comprises Part One of the present volume. In the academic year 1998-99 I had the opportunity to deliver this three-lecture series on four different occasions: as the Simon Lectures at the University ofToronto, as part ofmy annual visit to the University of Western Ontario, as the Hempel Lectures at Princeton University, and as the Kant Lectures at Stanford University. I was especially pleased to have had the opportunity to present the Hempel Lectures at Princeton, both because I had been a student of Hempel's at Princeton in the early 1970S and because my attempt at combining Kuhnian ideas with aspects of logical empiricism was complementary, in a way, to Hempel's own efforts to undertake a parallel accommodation in the later part of his philosophical career - beginning in the early 1970S and extending into the early 1990S [see, in particular, the essays from this period collected in Hempel (2000)]. Whereas Hempel had focussed on the kinship between the pragmatic and anti-formalistic dimensions of Kuhn's thought and Otto Neurath's naturalistic version of logical empiricism (by which Hempel himself had been significantly influenced during his early years in Berlin and Vienna), I was attempting to exploit the kinship between the Kuhnian notion of scientific paradigm and the Carnapian notion of linguistic framework so as to move scientific epistemology in a less pragmatically naturalistic and more Kantian direction.

Finally, I had the opportunity to discuss the ideas of the three lectures at the Fifth Göttinger Philosophisches Kolloquium at the University of Göttingen in June of 1999. In this colloquium series students in the Göttingen philosophical seminar study the work in progress of a particular philosopher during the academic year, followed by a three-day session at the end where papers on this work are presented by the students and intensively discussed with the philosopher in question. On this occasion I had provided the three lectures, together with related materials such as Friedman (1997a), (1997b), (1998), and (2000a). I am deeply indebted to the organizers of the colloquium, Felix Mühlholzer and Olaf Müller, and, most especially, to the students who prepared papers on my work: Marita Hübner, Lorenz Kähler, Tobias Klauk, Christoph Martel, Uwe Rose, Thomas Schmidt, Carsten
Schmidt-Samoa, Frank Tschepke, and Regina Wenninger. I am particularly grateful for this kind of critical feedback, for the ideas presented in the lectures very much represent work in progress and have by no means gelled into final form.

It is for this reason, above all, that I here offer the lectures together with a Part Two containing "Fruits of Discussion." Whereas the lectures themselves are presented basically unchanged (except for footnotes providing references and indications where my thinking has further developed in response to discussion), Part Two attempts a new systematic development of the ideas of the lectures, motivated, in large part, by the many helpful comments I received at all the occasions noted above. At Harvard I am especially indebted to comments from Stanley Cavell, Warren Goldfarb, Christine Korsgaard, Tim Maudlin, Hilary Putnam, and Thomas Scanlon; at the University of Toronto to James Robert Brown and Ian Hacking; at the University of Western Ontario to William Demopoulos, Robert DiSalle, William Harper, Wayne Myrvold, John Nicholas, and Itamar Pitowsky; at Princeton to Frank Arntzenius, Gordon Belot, Paul Benacerraf, John Burgess, Richard Jeffrey, Mark Johnston, Gideon Rosen, and Bas van Fraassen; at Stanford to Michael Bratman, Erik Curiel, John Etchemendy, Solomon Feferman, Peter Godfrey Smith, Yair Guttmann, Richard Rorty, Patrick Suppes, and Kenneth Taylor. In addition, I am also indebted to Henry Allison, Frederick Beiser, Domenico Bertoloni Meli, Paul Boghossian, William Boos, Tyler Burge, John Carriero, Andre Carus, Donald Davidson, Michael Dickson, Matthew Frank, Hartry Field, Arthur Fine, Alan Gabbey, Anil Gupta, Michael Heidelberger, David Kaplan, Noretta Koertge, Mark Lange, Elisabeth Lloyd, Edwin McCann, Thomas Nagel, William Newman, Calvin Normore, David Papineau, Paolo Parrini, Paul Pojman, Alan Richardson, Simon Saunders, Stephen Schiffer, Richard Sorrenson, Barry Stroud, Daniel Sutherland, William Talbott, Scott Tanona, Carol Voeller, Michael Williams, Mark Wilson, Rasmus Winther, John Worrall, and, as always, Graciela De Pierris. Finally, I would like to acknowledge James Mattingly for his work in preparing the index.

Note on references. In the bibliography I frequently list both an original edition and a second edition, reprinting, or translation. In citations I then give dates for both the original edition and the later one. In such cases I often give page numbers for both editions: thus "Carnap (1934/37, pp. 245-6/PP. 317-9)," for example, gives page numbers for both the original (1934) German edition and the (1937) English translation of Logical Syntax of Language. In some cases I give only one set of page numbers, which then refer to the later edition: thus "Quine (1951/53, pp. 42-3);' for example, gives page numbers for the (1953) reprinting of"Two Dogmas of Empiricism" in From a Logical Point of View.

= The Idea of a Scientific Philosophy
My theme is the relationship between science and philosophy. The two have been intimately related, of course, throughout our intellectual history. They were born together in the Greece of the sixth through third centuries before Christ, and flowered together once again in the late medieval, renaissance, and early modern periods of the thirteenth through seventeenth centuries, which ushered in the rise of both modern science and modem philosophy as we practice them today. Unlike today, however, in both of these earlier periods there was as yet no sharp differentiation between philosophy and the sciences. Just as the schools of Plato and Aristotle made fundamental contributions to mathematics, astronomy, biology, natural history, and meteorology, as well as to philosophy, so such early modern thinkers as Descartes and Leibniz, for example, made similarly fundamental contributions both to what we now call philosophy and to the emerging new sciences of the time. That what we now call physics was still called natural philosophy at this time is a very dear indication of the absence of a sharp distinction between them.

Soon thereafter, however, the boundary lines familiar to us today began to form. To be sure, there continued to be individuals - such as Hermann von Helmholtz, Ernst Mach, and Henri Poincare in the nineteenth century, for example - who made important contributions to both areas. And even in the vastly more specialized climate of the twentieth century, scientists whose work has had a particularly revolutionary character have continued to be involved with fundamental philosophical problems as well. In the case of Albert Einstein, for example, there is a volume ofthe Library ofLiving Philosophers devoted to him (alongside of such figures as John Dewey, George Santayana, Bertrand Russell, Ernst Cassirer, Karl Jaspers, Rudolf Carnap, Martin Buber, C. I. Lewis, Karl Popper, Gabriel Marcel, and W. V. Quine), entitled Albert Einstein: Philosopher-Scientist. Nevertheless, the professional boundaries were now clear - Helmholtz, Mach, and Poincare were clearly professional scientists rather than professional philosophers, for example - as well as the intellectual boundaries: in the Library of Living Philosophers Einstein's is the only volume entitled Philosopher-Scientist (a label that would never have appeared, as such, in the time of Descartes and Leibniz, say).

With the formation of these now familiar boundary lines came new intellectual problems, particularly for those who were now professional philosophers. Since philosophy was now clearly demarcated from science, at least professionally, what should be its relation to the sciences? Should it continue to maintain very close relations to the natural and mathematical sciences, as it did in the time of Descartes and Leibniz, say, or should it rather forsake these ties in favor of closer connections to more humanistic disciplines such as history, politics, religion, or the arts? (For one important aspect of the increasing specialization of the nineteenth and twentieth centuries is that it now appeared difficult, if not impossible, to maintain equally close ties with both.) Should philosophy, despite its professional demarcation from the sciences, nevertheless strive to imitate them intellectually? Should it strive, for example, to assimilate itself within the sciences, as a branch of psychology, say, or mathematical logic? Or, failing this, should it at least strive to make itself "scientific," by replacing the traditional endless strife of metaphysical systems with a new approach to philosophical problems capable of achieving the same degree of progress, and the same degree of consensus, that are found in the sciences themselves?

By considering some of the key historical episodes in the development of this situation, these are the questions I hope to shed light on here. In particular, I will consider a number of answers that have been proposed to these questions within a tradition that became known as "scientific philosophy." Although my focus is on the special relationship between philosophy and the sciences, our discussion will, I hope, have more general implications as well. For the question of such a relationship has become a troubling one within the humanities more generally during the same period, and for some of the same reasons. It was also in the context of the increasing specialization and professionalization of the late nineteenth century, for example, that the rift C. P. Snow later characterized as an opposition between "the two cultures" first arose, in the differentiation, within Wissenschaft in general (which term has a much more general meaning in German than our own term "science"), between the Naturwissenschaften and the Geisteswissenschaften. And the sense of tension and unease in the relationship between these two areas of course persists today. For many in the humanities, for example, Thomas Kuhn's The Structure of Scientific Revolutions brought a welcome sense of relief and vindication. Since Kuhn has shown that science has no special or privileged intellectual standing after all, so the argument goes, but is simply one more "disciplinary matrix" or intellectual community within our culture, we in the humanities need no longer worry about the presence or absence of a "scientific" foundation for our own disciplines. Indeed, since it is we in the humanities who have "culture" for our particular object of study, it is we, and not the scientists themselves, who are most competent to discuss the question of the ultimate "justification" or "legitimation" of the sciences. This line of thought has of course led inevitably to the recent "science wars," where even some scientists now feel themselves both intellectually and professionally on the defensive.

The concept of a "scientific philosophy" (or wissenschaftliche Philosophie) first developed in the mid nineteenth century, as a reaction against what was viewed as the excessively speculative and metaphysical character of post Kantian German idealism. One of the primary intellectual models of this movement was a celebrated address by Hermann von Helmholtz, "Über das Sehen des Menschen," delivered at the dedication of a monument to Kant at Königsberg in 1855 (Helmholtz at the time was professor of physiology at Königsberg.) Helmholtz begins by asking, on behalf of the audience, why a natural scientist like himself is speaking in honor of a philosopher. This question only arises, he says, because of the current deplorable climate of enmity and mutual distrust between the two fields - a climate which is due, in Helmhotz's opinion, to the entirely speculative system of Naturphilosophie that Schelling and Hegel have erected wholly independent of, and even in open hostility towards, the actual positive results of the natural sciences. What Helmholtz is now recommending, however, is a return to the close cooperation between the two fields exemplified in the work of Kant, who himself made significant contributions to natural science (in his nebular hypothesis put forward in 1755), and, in general, "stood in relation to the natural sciences together with the natural scientists on precisely the same fundamental principles."（此处有注释2） And it was this ecommendation that was enthusiastically embraced within the emerging "back to Kant!" movement, where it led to the idea that all metaphysics should be replaced by the new discipline of "epistemology" or "theory of knowledge" (Erkenntnistheorie), so that philosophy itself would now become "scientific." This movement then found its culmination in a new journal, the Vierteljahrsschrift für wissenschaftliche Philosophie, founded in 1877.（此处有注释3）

Now the charge that Helmholtz - and, following him, the rest of this "back to Kant!" movement for a scientific philosophy -leveled against the Naturphilosphie of the early nineteenth century is no doubt fundamentally unfair. Not only were the Naturphilosophen trying to respond intellectually to some of the key scientific developments of their time, developments in chemistry, electricity and magnetism, and energetics, for example, but it is also arguable that some of these key developments, including Helmholtz's own formulation of the conservation of energy in 1847, were themselves significantly influenced by Naturphilosophie.4 But what is of primary interest, from our present point of view, is the nature and character of the new scientific philosophy that was now being explicitly opposed to Naturphilosophie in particular and post-Kantian idealism in general. What relation is philosophy now supposed to bear to the sciences, and what does it mean for philosophy to become scientific in this way? What exactly is being recommended when we are told that philosophy should stand "in relation to the natural sciences together with the natural scientists on precisely the same fundamental principles"?

For Helmholtz himself this means that philosophy - that is, epistemology or the theory of knowledge - should work in cooperation with the latest psycho-physiological research in inquiring into the nature of the representations of our senses, and the relationship between these representations and the actual world to which they correspond. And it is for this reason that the body of his 1855 address is occupied almost exclusively with reporting on some of his own work in the psycho-physiology of vision, which he had begun as a student under Johannes MOller in Berlin. As he makes clear in his most mature presentation of his epistemology in "The Facts in Perception" of 1878, it is Helmholtz's view that philosophy considers the relationship between our representations and the external world from the inside out, as it were, while natural science - in this case psycho-physiology - considers the very same relationship from the outside in. Philosophy thus consider our knowledge from the mental or psychological side, while natural science considers it from the physical or physiological side:
（冒号后的引用下面再发）
The fundamental problem, which that time placed at the beginning of all science, was that of the theory of knowledge: 'What is truth in our intuition and thought? In what sense do our representations correspond to actuality?' Philosophy and natural science encounter this problem from two opposite sides; it is a common task of both. The first, which considers the mental side, seeks to separate out from our knowledge and representation what originates from the influences of the physical world, in order purely to establish what belongs to the mind's own activity. Natural science, by contrast, seeks to separate off what is definition, designation, form of representation, and hypothesis, in order purely to retain what belongs to the world of actuality, whose laws it seeks.（此处有原注5）

In both cases, however, our inquiry rests wholly and completely on the latest empirical findings of psychological and physiological research, and so, in the end, philosophy, for Helmholtz, is itself an empirical natural science - a branch of empirical psychology. In this way, Helmholtz anticipates the conception, popular in some circles today, that philosophy should become absorbed into cognitive psychology.

Helmholtz is thus being somewhat disingenuous in invoking the authority of Kant, and, more particularly, in recommending that we return to the close relationship between philosophy and natural science as Kant envisioned it. For Kant himself held that philosophy has a special "transcendental" status that sharply differentiates it from all empirical science, including, and indeed especially, empirical psychology. For example, in leading up to a characterization of "transcendental logic" - another name for what he is here calling "transcendental philosophy" - Kant explains that logic "as pure ... has no empirical principles, and hence borrows nothing (as one has sometimes supposed) from psychology, which thus as no influence at all on the canon of the understanding.» And a few pages later Kant makes a remark which, as he says, "extends its influence over all the following considerations, and which one must bear well in mind":

[N]ot every a priori cognition should be called transcendental,but only that through which we know that and how certain representations (intuitions or concepts) are applied wholly a priori, or are possible (that is, [through which we know] the possibility or the a priori employment ofthe cognition). Therefore, neither space nor any a priori geometrical determination thereof is a transcendental representation, but what can alone be called transcendental is the knowledge that these representations are not at all of empirical origin, and the possibility that they can nevertheless relate a priori to objects of experience.(A56/B80-1)（此处有原文注6：All references to the Critique of Pure Reason are given by the standard pagination of the first (A) and second (B) editions. The earlier cited remark about the purity of logic occurs at A54/1378）

Philosophy, as a "transcendental" inquiry, is not only distinct from all empirical science, but it is also distinct from those elements of pure a priori knowledge, such as geometry, for example, which are present in the sciences themselves. Whereas each of the first-level sciences, whether empirical or a priori, has its own characteristic objects, philosophy, as a second-level or meta-level discipline, has no such objects of its own, but rather concerns the nature and possibility of our *representations* of these objects. The distinctive subject matter of philosophy is thus our *knowledge* of these first-level objects. As Kant puts it elsewhere (B25): "I term all cognition transcendental which occupies itself in general, not so much with objects, but rather with our mode of cognition of objects, in so far as this is supposed to be possible a priori."

Indeed, this Kantian distinction between first-level scientific inquiries and the distinctively philosophical "transcendental" inquiry is actually the historical source for the intellectual differentiation between philosophy and the sciences which is now familiar today. The rationalist philosophers ofthe seventeenth century, such as Descartes and Leibniz, had distinguished between physics or natural philosophy, on the one hand, and metaphysics or "first philosophy," on the other. But they by no means meant by this a distinction between two essentially different types or levels of inquiry in the Kantian sense. Rather, just as physics or natural philosophy studies the visible or corporeal part of the universe, metaphysics or "first philosophy" studies the invisible or incorporeal part - that is, God and the soul. And it is precisely by articulating the structure of the invisible or incorporeal part of the universe that "first philosophy" or metaphysics can then provide a rational foundation for physics: a rational foundation, that is, for the new mathematical natural philosophy to which these rationalist philosophers were themselves making vitally important contributions. In their intellectual enterprise - that of articulating the rational structure of the universe as a whole - "first philosophy" and natural philosophy are thus entirely continuous.
