
// 内页

Stanford Kant Lectures
The Stanford Kant Lectures are an invited series sponsored by the Stanford
University department of philosophy. Philosophers are invited to reflect on
the state of the art in their field and to report on current research in a way that
is accessible to the broader community of scholars, educators, students and
the public at large. Topics range from Kant's philosophy of science to the
nature of human desire. The Kant Lecturer is selected by the department in
light of its judgment that the speaker has a deep understanding ofthe issues in
his or her field, and a vision of their connection to questions of lasting concern across academic disciplines.

// 内页
MICHAEL FRIEDMAN
Dynamics ofReason
The 1999 Kant Lectures at Stanford University

CSLI Publications
Center for the Study of
Language and Information
Stanford, California

// 图书信息
Library of Congress Cataloging-in-Publication Data
Friedman, Michael, 1947-
Dynamics of reason / Michael Friedman.
p. cm.
(Stanford Kant Lectures)
Includes bibliographical references and index.
ISBN 1-57586-291-3 (alk. paper)-ISBN 1-57586-292-1 (pbk.: alk. paper)
1. Science-Philosophy. I. Title
Q175 .F892 2001
501-dc21
2001017171

// 纪念
in memory of
Carl Gustav ("Peter") Hempel
teacher, mentor, friend

// 引言
It might be supposed that [reason’s demand for systematic unity and simplicity] is merely an economical contrivance whereby reason seeks to save itself all possible trouble, a hypothetical attempt, which, if it succeeds, will, through the unity thus attained, impart probability to the presumed principle of explanation. But such a selfish purpose can very easily be distinguished from the Idea. For in conformity with the Idea everyone presupposes that this unity of reason accords with nature itself, and that reason - although indeed unable to determine the limits of this unity - does not here beg but command.

// 目录
Contents
Preface xi
Part One: The Lectures
I. The Idea of a Scientific Philosophy 3
II. Historical Perspectives on the Stratification of Knowledge 25
III. Rationality, Revolution, and the Community of Inquiry 47
Part Two: Fruits of Discussion
1. The Relativized A Priori 71
2. A Priori Principles and Empirical Evidence 83
3. Rationality and Revolution 93
4. The Role of Philosophy 105
5. Other Problems, Other Sciences 117
References 131
Index 137

// 前言
= Preface

For the past twenty years I have been pursuing historical studies on the relationship between developments in scientific philosophy from Kant (in the late eighteenth century) to logical empiricism (in the early twentieth) and concurrent developments taking place within the sciences, principally within the exact sciences of logic, mathematics, and mathematical physics. These studies concentrated on Kant's involvement with the sciences of his time (Euclidean geometry and Newtonian physics, for example) and the various ways in which late nineteenth and early twentieth century revolutionary changes within these sciences (non-Euclidean geometry and relativistic physics, for example) motivated early twentieth century logical empiricists to undertake similarly revolutionary changes in the Kantian and neo-Kantian philosophy oftheir time. My primary aim was to depict the deep and intricate connections between the historical development of scientific philosophy, on the one hand, and the parallel evolution of the exact sciences themselves, on the other.

I did not, however, attempt to draw substantive morals for our contemporary philosophical predicament from these historical studies. Indeed, my dominant tone was rather unhopeful. Kant's original philosophical synthesis had failed due to unforeseen revolutionary changes within the sciences, and the logical empiricists's radical revision of this synthesis had also failed to do
justice to the very rapid changes taking place within early twentieth century science. In response to this situation I offered only the indeterminate suggestion that we, too, should attempt a fruitful interaction between contemporary philosophical practice and developments within the sciences themselves, and the pessimistic conclusion that we now have no idea how to go about this
given the twin failures of Kantianism and logical empiricism.

In the mid to late 1990s I began to see a way out ofthis dilemma. It was not yet clear how one could preserve any kind of commitment to a Kantian or neo-Kantian conception of a priori principles in the exact sciences (as in Kant's original conception of the synthetic a priori, for example, or Rudolf Carnap's version of the analytic a priori developed in the logical empiricist
tradition), but I was convinced, at the same time, that the dominant viewpoint within contemporary scientific philosophy – some or another version of naturalistic epistemological holism – is entirely incapable of providing an adequate philosophical perspective on these sciences. The idea I then came up with, against this twofold background, was that one could attempt to combine basic aspects of Carnap's philosophy of formal languages or linguistic frameworks with fundamental features of Thomas Kuhn's much less formal theory of scientific revolutions. And in this way, more specifically, one could articulate a conception of dynamical or relativized a priori principles within an historical account of the conceptual evolution of the sciences rather than a purely syntactic or semantic account of the formal language(s) of the sciences. One could thus reap the benefits of Kuhnian conceptual history while simultaneously avoiding the drawbacks of Carnapian formal Wissenschaftslogik. In particular, W. V. Quine's well-known and widely accepted attack on the Carnapian conception of analytic truth need no longer compel us to adopt a thoroughgoing epistemological holism according to which there is nothing left of the a priori at all.

In 1997 I had the opportunity to deliver the Whitehead Lecture at Harvard University and the Presidential Address to the Central Division of the American Philosophical Association. I chose, for both occasions, the topic of "Philosophical Naturalism" [Friedman (1997a)], where my aim, in particular, was to attack the contemporary consensus in favor of Quinean epistemological holism on behalf of a neo-Kantian (and historicized) conception of relativized a priori principles. I found, at the same time, that I was thereby able to develop a new positive conception of the peculiar role of scientific philosophy vis-a.-vis the sciences, as a distinctive meta-scientific level of thought or discourse making its own indispensable contribution to the rationality of radical conceptual revolutions (Kuhnian "paradigm-shifts") taking place within the sciences themselves. I further developed these ideas in a second paper, "On the Idea of a Scientific Philosophy:' which I then delivered as part of a series on "Science and Defining the Human" at Northwestern University, as the Stice Lecture at the University of Washington, as a Distinguished Visitor at the University of California at Riverside, as the Jacobson Lecture at the University of London, the Hall Lecture at the University of Iowa, and the Werkmeister Lecture at Florida State University.

This last paper then became the first lecture in the three-lecture series that comprises Part One of the present volume. In the academic year 1998-99 I had the opportunity to deliver this three-lecture series on four different occasions: as the Simon Lectures at the University ofToronto, as part ofmy annual visit to the University of Western Ontario, as the Hempel Lectures at Princeton University, and as the Kant Lectures at Stanford University. I was especially pleased to have had the opportunity to present the Hempel Lectures at Princeton, both because I had been a student of Hempel's at Princeton in the early 1970S and because my attempt at combining Kuhnian ideas with aspects of logical empiricism was complementary, in a way, to Hempel's own efforts to undertake a parallel accommodation in the later part of his philosophical career - beginning in the early 1970S and extending into the early 1990S [see, in particular, the essays from this period collected in Hempel (2000)]. Whereas Hempel had focussed on the kinship between the pragmatic and anti-formalistic dimensions of Kuhn's thought and Otto Neurath's naturalistic version of logical empiricism (by which Hempel himself had been significantly influenced during his early years in Berlin and Vienna), I was attempting to exploit the kinship between the Kuhnian notion of scientific paradigm and the Carnapian notion of linguistic framework so as to move scientific epistemology in a less pragmatically naturalistic and more Kantian direction.

Finally, I had the opportunity to discuss the ideas of the three lectures at the Fifth Göttinger Philosophisches Kolloquium at the University of Göttingen in June of 1999. In this colloquium series students in the Göttingen philosophical seminar study the work in progress of a particular philosopher during the academic year, followed by a three-day session at the end where papers on this work are presented by the students and intensively discussed with the philosopher in question. On this occasion I had provided the three lectures, together with related materials such as Friedman (1997a), (1997b), (1998), and (2000a). I am deeply indebted to the organizers of the colloquium, Felix Mühlholzer and Olaf Müller, and, most especially, to the students who prepared papers on my work: Marita Hübner, Lorenz Kähler, Tobias Klauk, Christoph Martel, Uwe Rose, Thomas Schmidt, Carsten
Schmidt-Samoa, Frank Tschepke, and Regina Wenninger. I am particularly grateful for this kind of critical feedback, for the ideas presented in the lectures very much represent work in progress and have by no means gelled into final form.

It is for this reason, above all, that I here offer the lectures together with a Part Two containing "Fruits of Discussion." Whereas the lectures themselves are presented basically unchanged (except for footnotes providing references and indications where my thinking has further developed in response to discussion), Part Two attempts a new systematic development of the ideas of the lectures, motivated, in large part, by the many helpful comments I received at all the occasions noted above. At Harvard I am especially indebted to comments from Stanley Cavell, Warren Goldfarb, Christine Korsgaard, Tim Maudlin, Hilary Putnam, and Thomas Scanlon; at the University of Toronto to James Robert Brown and Ian Hacking; at the University of Western Ontario to William Demopoulos, Robert DiSalle, William Harper, Wayne Myrvold, John Nicholas, and Itamar Pitowsky; at Princeton to Frank Arntzenius, Gordon Belot, Paul Benacerraf, John Burgess, Richard Jeffrey, Mark Johnston, Gideon Rosen, and Bas van Fraassen; at Stanford to Michael Bratman, Erik Curiel, John Etchemendy, Solomon Feferman, Peter Godfrey Smith, Yair Guttmann, Richard Rorty, Patrick Suppes, and Kenneth Taylor. In addition, I am also indebted to Henry Allison, Frederick Beiser, Domenico Bertoloni Meli, Paul Boghossian, William Boos, Tyler Burge, John Carriero, Andre Carus, Donald Davidson, Michael Dickson, Matthew Frank, Hartry Field, Arthur Fine, Alan Gabbey, Anil Gupta, Michael Heidelberger, David Kaplan, Noretta Koertge, Mark Lange, Elisabeth Lloyd, Edwin McCann, Thomas Nagel, William Newman, Calvin Normore, David Papineau, Paolo Parrini, Paul Pojman, Alan Richardson, Simon Saunders, Stephen Schiffer, Richard Sorrenson, Barry Stroud, Daniel Sutherland, William Talbott, Scott Tanona, Carol Voeller, Michael Williams, Mark Wilson, Rasmus Winther, John Worrall, and, as always, Graciela De Pierris. Finally, I would like to acknowledge James Mattingly for his work in preparing the index.

Note on references. In the bibliography I frequently list both an original edition and a second edition, reprinting, or translation. In citations I then give dates for both the original edition and the later one. In such cases I often give page numbers for both editions: thus "Carnap (1934/37, pp. 245-6/PP. 317-9)," for example, gives page numbers for both the original (1934) German edition and the (1937) English translation of Logical Syntax of Language. In some cases I give only one set of page numbers, which then refer to the later edition: thus "Quine (1951/53, pp. 42-3);' for example, gives page numbers for the (1953) reprinting of"Two Dogmas of Empiricism" in From a Logical Point of View.

= The Idea of a Scientific Philosophy
My theme is the relationship between science and philosophy. The two have been intimately related, of course, throughout our intellectual history. They were born together in the Greece of the sixth through third centuries before Christ, and flowered together once again in the late medieval, renaissance, and early modern periods of the thirteenth through seventeenth centuries, which ushered in the rise of both modern science and modem philosophy as we practice them today. Unlike today, however, in both of these earlier periods there was as yet no sharp differentiation between philosophy and the sciences. Just as the schools of Plato and Aristotle made fundamental contributions to mathematics, astronomy, biology, natural history, and meteorology, as well as to philosophy, so such early modern thinkers as Descartes and Leibniz, for example, made similarly fundamental contributions both to what we now call philosophy and to the emerging new sciences of the time. That what we now call physics was still called natural philosophy at this time is a very dear indication of the absence of a sharp distinction between them.

Soon thereafter, however, the boundary lines familiar to us today began to form. To be sure, there continued to be individuals - such as Hermann von Helmholtz, Ernst Mach, and Henri Poincare in the nineteenth century, for example - who made important contributions to both areas. And even in the vastly more specialized climate of the twentieth century, scientists whose work has had a particularly revolutionary character have continued to be involved with fundamental philosophical problems as well. In the case of Albert Einstein, for example, there is a volume ofthe Library ofLiving Philosophers devoted to him (alongside of such figures as John Dewey, George Santayana, Bertrand Russell, Ernst Cassirer, Karl Jaspers, Rudolf Carnap, Martin Buber, C. I. Lewis, Karl Popper, Gabriel Marcel, and W. V. Quine), entitled Albert Einstein: Philosopher-Scientist. Nevertheless, the professional boundaries were now clear - Helmholtz, Mach, and Poincare were clearly professional scientists rather than professional philosophers, for example - as well as the intellectual boundaries: in the Library of Living Philosophers Einstein's is the only volume entitled Philosopher-Scientist (a label that would never have appeared, as such, in the time of Descartes and Leibniz, say).

With the formation of these now familiar boundary lines came new intellectual problems, particularly for those who were now professional philosophers. Since philosophy was now clearly demarcated from science, at least professionally, what should be its relation to the sciences? Should it continue to maintain very close relations to the natural and mathematical sciences, as it did in the time of Descartes and Leibniz, say, or should it rather forsake these ties in favor of closer connections to more humanistic disciplines such as history, politics, religion, or the arts? (For one important aspect of the increasing specialization of the nineteenth and twentieth centuries is that it now appeared difficult, if not impossible, to maintain equally close ties with both.) Should philosophy, despite its professional demarcation from the sciences, nevertheless strive to imitate them intellectually? Should it strive, for example, to assimilate itself within the sciences, as a branch of psychology, say, or mathematical logic? Or, failing this, should it at least strive to make itself "scientific," by replacing the traditional endless strife of metaphysical systems with a new approach to philosophical problems capable of achieving the same degree of progress, and the same degree of consensus, that are found in the sciences themselves?

By considering some of the key historical episodes in the development of this situation, these are the questions I hope to shed light on here. In particular, I will consider a number of answers that have been proposed to these questions within a tradition that became known as "scientific philosophy." Although my focus is on the special relationship between philosophy and the sciences, our discussion will, I hope, have more general implications as well. For the question of such a relationship has become a troubling one within the humanities more generally during the same period, and for some of the same reasons. It was also in the context of the increasing specialization and professionalization of the late nineteenth century, for example, that the rift C. P. Snow later characterized as an opposition between "the two cultures" first arose, in the differentiation, within Wissenschaft in general (which term has a much more general meaning in German than our own term "science"), between the Naturwissenschaften and the Geisteswissenschaften. And the sense of tension and unease in the relationship between these two areas of course persists today. For many in the humanities, for example, Thomas Kuhn's The Structure of Scientific Revolutions brought a welcome sense of relief and vindication. Since Kuhn has shown that science has no special or privileged intellectual standing after all, so the argument goes, but is simply one more "disciplinary matrix" or intellectual community within our culture, we in the humanities need no longer worry about the presence or absence of a "scientific" foundation for our own disciplines. Indeed, since it is we in the humanities who have "culture" for our particular object of study, it is we, and not the scientists themselves, who are most competent to discuss the question of the ultimate "justification" or "legitimation" of the sciences. This line of thought has of course led inevitably to the recent "science wars," where even some scientists now feel themselves both intellectually and professionally on the defensive.

The concept of a "scientific philosophy" (or wissenschaftliche Philosophie) first developed in the mid nineteenth century, as a reaction against what was viewed as the excessively speculative and metaphysical character of post Kantian German idealism. One of the primary intellectual models of this movement was a celebrated address by Hermann von Helmholtz, "Über das Sehen des Menschen," delivered at the dedication of a monument to Kant at Königsberg in 1855 (Helmholtz at the time was professor of physiology at Königsberg.) Helmholtz begins by asking, on behalf of the audience, why a natural scientist like himself is speaking in honor of a philosopher. This question only arises, he says, because of the current deplorable climate of enmity and mutual distrust between the two fields - a climate which is due, in Helmhotz's opinion, to the entirely speculative system of Naturphilosophie that Schelling and Hegel have erected wholly independent of, and even in open hostility towards, the actual positive results of the natural sciences. What Helmholtz is now recommending, however, is a return to the close cooperation between the two fields exemplified in the work of Kant, who himself made significant contributions to natural science (in his nebular hypothesis put forward in 1755), and, in general, "stood in relation to the natural sciences together with the natural scientists on precisely the same fundamental principles."（此处有注释2） And it was this ecommendation that was enthusiastically embraced within the emerging "back to Kant!" movement, where it led to the idea that all metaphysics should be replaced by the new discipline of "epistemology" or "theory of knowledge" (Erkenntnistheorie), so that philosophy itself would now become "scientific." This movement then found its culmination in a new journal, the Vierteljahrsschrift für wissenschaftliche Philosophie, founded in 1877.（此处有注释3）

Now the charge that Helmholtz - and, following him, the rest of this "back to Kant!" movement for a scientific philosophy -leveled against the Naturphilosphie of the early nineteenth century is no doubt fundamentally unfair. Not only were the Naturphilosophen trying to respond intellectually to some of the key scientific developments of their time, developments in chemistry, electricity and magnetism, and energetics, for example, but it is also arguable that some of these key developments, including Helmholtz's own formulation of the conservation of energy in 1847, were themselves significantly influenced by Naturphilosophie.4 But what is of primary interest, from our present point of view, is the nature and character of the new scientific philosophy that was now being explicitly opposed to Naturphilosophie in particular and post-Kantian idealism in general. What relation is philosophy now supposed to bear to the sciences, and what does it mean for philosophy to become scientific in this way? What exactly is being recommended when we are told that philosophy should stand "in relation to the natural sciences together with the natural scientists on precisely the same fundamental principles"?

For Helmholtz himself this means that philosophy - that is, epistemology or the theory of knowledge - should work in cooperation with the latest psycho-physiological research in inquiring into the nature of the representations of our senses, and the relationship between these representations and the actual world to which they correspond. And it is for this reason that the body of his 1855 address is occupied almost exclusively with reporting on some of his own work in the psycho-physiology of vision, which he had begun as a student under Johannes MOller in Berlin. As he makes clear in his most mature presentation of his epistemology in "The Facts in Perception" of 1878, it is Helmholtz's view that philosophy considers the relationship between our representations and the external world from the inside out, as it were, while natural science - in this case psycho-physiology - considers the very same relationship from the outside in. Philosophy thus consider our knowledge from the mental or psychological side, while natural science considers it from the physical or physiological side:
（冒号后的引用下面再发）
The fundamental problem, which that time placed at the beginning of all science, was that of the theory of knowledge: 'What is truth in our intuition and thought? In what sense do our representations correspond to actuality?' Philosophy and natural science encounter this problem from two opposite sides; it is a common task of both. The first, which considers the mental side, seeks to separate out from our knowledge and representation what originates from the influences of the physical world, in order purely to establish what belongs to the mind's own activity. Natural science, by contrast, seeks to separate off what is definition, designation, form of representation, and hypothesis, in order purely to retain what belongs to the world of actuality, whose laws it seeks.（此处有原注5）

In both cases, however, our inquiry rests wholly and completely on the latest empirical findings of psychological and physiological research, and so, in the end, philosophy, for Helmholtz, is itself an empirical natural science - a branch of empirical psychology. In this way, Helmholtz anticipates the conception, popular in some circles today, that philosophy should become absorbed into cognitive psychology.

Helmholtz is thus being somewhat disingenuous in invoking the authority of Kant, and, more particularly, in recommending that we return to the close relationship between philosophy and natural science as Kant envisioned it. For Kant himself held that philosophy has a special "transcendental" status that sharply differentiates it from all empirical science, including, and indeed especially, empirical psychology. For example, in leading up to a characterization of "transcendental logic" - another name for what he is here calling "transcendental philosophy" - Kant explains that logic "as pure ... has no empirical principles, and hence borrows nothing (as one has sometimes supposed) from psychology, which thus as no influence at all on the canon of the understanding.» And a few pages later Kant makes a remark which, as he says, "extends its influence over all the following considerations, and which one must bear well in mind":

[N]ot every a priori cognition should be called transcendental,but only that through which we know that and how certain representations (intuitions or concepts) are applied wholly a priori, or are possible (that is, [through which we know] the possibility or the a priori employment ofthe cognition). Therefore, neither space nor any a priori geometrical determination thereof is a transcendental representation, but what can alone be called transcendental is the knowledge that these representations are not at all of empirical origin, and the possibility that they can nevertheless relate a priori to objects of experience.(A56/B80-1)（此处有原文注6：All references to the Critique of Pure Reason are given by the standard pagination of the first (A) and second (B) editions. The earlier cited remark about the purity of logic occurs at A54/1378）

Philosophy, as a "transcendental" inquiry, is not only distinct from all empirical science, but it is also distinct from those elements of pure a priori knowledge, such as geometry, for example, which are present in the sciences themselves. Whereas each of the first-level sciences, whether empirical or a priori, has its own characteristic objects, philosophy, as a second-level or meta-level discipline, has no such objects of its own, but rather concerns the nature and possibility of our *representations* of these objects. The distinctive subject matter of philosophy is thus our *knowledge* of these first-level objects. As Kant puts it elsewhere (B25): "I term all cognition transcendental which occupies itself in general, not so much with objects, but rather with our mode of cognition of objects, in so far as this is supposed to be possible a priori."

Indeed, this Kantian distinction between first-level scientific inquiries and the distinctively philosophical "transcendental" inquiry is actually the historical source for the intellectual differentiation between philosophy and the sciences which is now familiar today. The rationalist philosophers ofthe seventeenth century, such as Descartes and Leibniz, had distinguished between physics or natural philosophy, on the one hand, and metaphysics or "first philosophy," on the other. But they by no means meant by this a distinction between two essentially different types or levels of inquiry in the Kantian sense. Rather, just as physics or natural philosophy studies the visible or corporeal part of the universe, metaphysics or "first philosophy" studies the invisible or incorporeal part - that is, God and the soul. And it is precisely by articulating the structure of the invisible or incorporeal part of the universe that "first philosophy" or metaphysics can then provide a rational foundation for physics: a rational foundation, that is, for the new mathematical natural philosophy to which these rationalist philosophers were themselves making vitally important contributions. In their intellectual enterprise - that of articulating the rational structure of the universe as a whole - "first philosophy" and natural philosophy are thus entirely continuous.

Kant, by contrast, is breaking decisively with this tradition. For him, (theoretical) rational knowledge of incorporeal objects, and, in particular, of God and the soul, is completely impossible for us.（此处有原注7：Kant does believe, however, that we have practical access to the supersensible through our experience of the moral law. This is the point of his famous dictum that he "had to destroy knowledge [Wissen] in order to procure a place for belief[Glauben]" (Bxxx).） The only possible objects of our human knowledge are "appearances," that is, objects in space and time interacting with one another in accordance with the causal laws of the new mathematical natural science. So metaphysics or «first philosophy" in the sense of seventeenth century rationalism is also entirely impossible. What can replace this hopeless enterprise, however, is a new "transcendental" inquiry into the *conditions of possibility* of our first-level knowledge of objects in space and time (the only genuine objects of knowledge there now are) supplied by mathematical natural science. In this way, by renouncing all claims on the supersensible, and redirecting our attention rather to the necessary conditions which make possible natural scientific knowledge (the only genuine knowledge of objects we now have), philosophy or metaphysics can finally leave behind the "mock combats" of the schools, and itself enter into "the secure path of a science."（此处有原注8：See note 11 below.） In this way, too, philosophy can give a rational foundation, but in an entirely new sense, for the natural scientific knowledge whose conditions of possibility it investigates.

Kant's new concern with what he calls conditions of possibility is fundamentally shaped by the scientific context of the eighteenth century - the age of the triumph of Newtonianism. The rationalist thinkers of the seventeenth century had acted as contributors, apologists, and propagandists for the mechanical natural philosophy: the inspiring vision, fueled by Copernicanism and the example of Galileo, of a precise mathematical description of all of the phenomena of nature under a single set of mathematical laws uniting the earth and the heavens, to be achieved by an atomistic or corpuscular theory of matter that reduced all natural changes to the motions and mutual impacts of the constituent particles. But the rationalist defense of the mechanical philosophy was also highly programmatic in character, in so far as nothing even approaching such a unified mathematical description was actually produced. Only with Newton, in fact, was even the very first step of this program, the synthesis, under a common set of dynamical laws, of celestial astronomy with aspects of terrestrial physics (namely, those due to gravity) actually achieved.

Yet this Newtonian synthesis also raised serious conceptual problems. In the first place, it portrayed gravitational interaction as an immediate action at a distance across arbitrarily large empty spaces, thereby breaking with the fundamental tenet of the mechanical philosophy that all action should take place by contact. So it appeared that we were either left with a commitment to just the kind of "occult quality" that the mechanical philosophy had dedicated itself to overcome (a primitive *attraction*), or forced to acquiesce in a merely empirical and phenomenological physics that renounced all inquiry into "true causes." In the second place, however, and even more seriously, Newton's physics was deliberately and self-consciously erected on the concepts of absolute space, time, and motion. These concepts were also entirely unacceptable to the seventeenth century rationalism which fueled the mechanical philosophy - on the basis of the sharp division, noted above, between the visible or corporeal part of the universe and the invisible or incorporeal part. For absolute space and time appeared to occupy a completely untenable intermediate position, as incorporeal but nonetheless physical. (And it was precisely this intermediate status that led to the traditional puzzles about the relationships between space, time, and divinity.)

In the eighteenth century, then, Newton's physics was an unqualified success in both mathematical and empirical terms, but there remained serious conceptual problems concerning whether and how this brilliantly successful theory actually made rational sense. Kant's problem, accordingly, was not to sketch a program for a new mathematical physics, but rather to explain how our actual mathematical physics, the mathematical physics of Newton, was itself possible in the first place. And his answer, in the briefest possible terms, is that the concepts of space, time, motion, action, and force do not function to describe a metaphysical realm of entities or "true causes" lying behind the phenomena. Nor are they simply abstractions from our experience, which we can then apply to the phenomena because we have already found them there. Rather, such concepts as space, time, motion, action, and force are a priori forms or constructions of our own, on the basis of which alone we can coherently order the phenomena of nature into a unified and law governed spatiotemporal totality. Absolute space, for example, is not a metaphysical entity, a great empty "container," existing behind the phenomena independently of all material content. Yet, as the success of Newton's physics dramatically shows, we cannot simply dispense with it either, as an empty concept with no empirical application. On the contrary, we apply this concept empirically in constructing approximations to a privileged frame of reference at absolute rest - as a first approximation, for example, Newton, in the Principia, has himself constructed the center of mass frame of the solar system.（此处有原注9： For Kant this procedure is then continued indefinitely: from the center of mass of the solar system to the center of mass of the Milky Way galaxy, from there to the center of mass of a system of such galaxies, from there to the center of mass of a system of such systems, and so on. For discussion of Kant's analysis of Newtonian physics with special attention to the problem of absolute space, time, and motion see Friedman (1992, chapters 3 and 4). ） And action at a distance, despite its violation of the strictures of the mechanical philosophy, is a similarly necessary concept, in its realization by universal gravitation, for empirically establishing the temporal simultaneity of arbitrarily distant events. （此处有原注10：Kant's Third Analogy of Experience depicts the most general conditions for establishing the temporal relation of simultaneity (whereas the First and Second deal with duration and succession respectively).ln the Metaphysical Foundations of Natural Science (1786) the Third Analogy is realized or instantiated by the Newtonian third law of motion - the equality of action and reaction. Universal gravitation is then an even more specific realization of this last principle. For further discussion see Friedman (1992), and compare also Part Two, section 2 below (in particular note 23).）

For Kant, then, Newtonian physics is not simply a pragmatically successful scheme for ordering and predicting the phenomena. It also counts as a model or paradigm for the coherent rational comprehension of nature, because it injects a priori forms, constructions, or categories of our own - which, for Kant, express universal capacities of the human mind - into our experience of nature. It is in this way, and this way alone, for Kant, that we can rationally explain how such pragmatic empirical success is actually possible in the first place. And it is in this way, too, that we can finally set what was previously called metaphysics or "first philosophy" onto "the secure path of a science," where we leave behind its former condition of "random groping," "mock combat," and utter lack of unanimity:

With respect to the question of unanimity among the adherents of metaphysics in their assertions, it is still so far from this that it is rather a battle ground, which seems to be quite peculiarly destined to exert its forces in mock combats, and in which no combatant has ever yet been able to win even the smallest amount of ground, and to base on his victory an enduring possession. There is therefore no doubt that its procedure has, until now, been a merely random groping, and, what is worst of all, among mere concepts. (Bxiv-v)（此处有原注11：In the preceding pages Kant describes how logic, mathematics, and natural science have been placed on "the secure path of a science," and in the succeeding pages he explains how metaphysics can now be placed on this path in a similar fashion (“by a single and sudden revolution") through precisely his own revolution in philosophy.）

By renouncing all claims to a special, as it were, "supernatural" domain of objects of its own, and rather confining itself to the articulation of the necessary conditions of possibility of the natural and mathematical sciences, philosophy, although not itself a science in the same sense, can nevertheless achieve stable and definitive results, and thus finally become, in this sense, scientific.

Let us now move forward to the year 1921, the centenary year of Hermann von Helmholtz's birth. Helmholtz's remarkable and wide-ranging scientific achievements, in energetics, physiological psychology, the foundations of geometry, electrodynamics, and epistemology, were celebrated in a variety of memorial addresses, journal issues, monographs, and the like, including an address given by the philosopher Moritz Schlick at the University of Berlin, entitled "Helmholtz als Erkenntnistheoritiker." Schlick had earlier earned a doctorate in theoretical physics under Max Planck at Berlin, but soon thereafter decided to pursue a career in philosophy instead. His Habilitation in philosophy, on "The Essence of Truth in Modern Logic," was published in 1910 in the *Vierteljahrsschrift für wissenschaftliche Philosophie und Soziologie* (which the *Vierteljahrsschrift für wissenschaftliche Philosophie* had turned into in 1901). Schlick then became the leading philosophical proponent and expositor of Einstein's new theory of relativity with the publication of his extremely influential monograph, *Space and Time in Contemporary Physics*, which went through four editions between 1917 and 1922. In 1922, largely on the strength of his work on the philosophical significance of the theory of relativity, which had been enthusiastically endorsed by Einstein himself, Schlick was named to the Chair for the Philosophy of the Inductive Sciences previously occupied by the scientists Ernst Mach and Ludwig Boltzmann at the University of Vienna, where he became the leader and guiding spirit of what we now know as the Vienna Circle of logical positivists. We might say, in this sense, that Schlick was the very first professional scientific philosopher.

Just as Helmholtz, in his dedicatory address on human vision of 1855, invokes the authority of Kant on behalf of his own conception of scientific philosophy, Schlick, in his memorial address of 1921, invokes the authority of Helmholtz, and the example of Helmholtz's 185; address, on behalf of his conception of the relation of science to philosophy. All great scientists, according to Schlick, "think every problem with which they are concerned up to the end, and the end of every problem lies in philosophy." By beginning with special problems of the special sciences, we ascend step by step to "the ultimate attainable principles ... which, because of their generality, no longer belong to any special science, but rather lie beyond them in the sphere of the general theory of science, in philosophy, in the theory of knowledge." Physics, for example, "penetrates only ... to certain ultimate concepts and presuppositions - such as space, time, causality ... whose illumination and justification must remain left to philosophy."（此处有原注12：Schlick (1922/78. pp. 29-30/p. 335).） Yet, as Schlick makes clear elsewhere, this does not mean that philosophy is a separate discipline from the sciences:

Philosophy is not an independent science that would be placed next to or above the individual disciplines. Rather, what is philosophical is found in all the sciences as their true soul, in virtue of which they first become sciences at all. Every particular field of knowledge, every special form of knowing, presupposes the most general principles into which it flows and without which it would not be knowledge. Philosophy is nothing other than the system of these principles, which branches out and penetrates the system of all knowledge and thereby gives it stability; it therefore has its home in all the sciences. （此处有原注13：Preface to General Theory of Knowledge: Schlick (1918/85, p. vii/po v).）

Philosophy, for Schlick, does not have any special relation to psychology. It is not, as it was for Helmholtz, especially concerned with the psycho-physiological mechanisms of human sense perception. Philosophy is rather concerned with the foundations or ultimate principles of each and every science, whereby each of the special sciences takes its own particular place in the total system of knowledge. Philosophy, we might say, supplies the foundational and systematic core of each of the special sciences; it is neither a meta-science (as it was for Kant) nor particularly connected with any individual special science (as it was for Helmholtz).

Nevertheless, the ultimate scientific principles with which Schlick was himself especially concerned, as he indicates in his 1921 address, are the principles of Einstein's new physics - principles of "space, time, causality." And, with respect to these principles, it is not too much to say that Schlick aimed to do for Einstein's physics what Kant had done for Newton's, namely, to explain and exhibit the special features of this physics that make it a model or paradigm of coherent rational knowledge of nature. One central implication of this new physics, however, is that Kant's conception of natural knowledge, as framed by universal forms or categories of the human mind, taken to be rigidly fixed for all time, cannot, after all, be correct. For it is precisely the Newtonian conceptions of space, time, motion, and interaction that Einstein has now rejected and replaced; and so these particular ultimate principles in no way have the status Kant had attributed to them. Yet this does not mean, as Ernst Mach would have it, for example, that physics can simply be abstracted or generated from sense experience and from sense experience alone. On the contrary, we still need superordinate and highly mathematical first principles in physics - principles that must be injected into our experience of nature before such experience can teach us anything at all. But these principles do not express a priori fixed features of the human mind, as Kant would have it. They rather have the status of what Henri Poincare, in his own work on the philosophical foundations of geometry, called "conventions" - free *choices* of our own needed to bridge the irreducible gulf between our crude and approximate sensory experience and our precise mathematical descriptions of nature.

So things stood for Schlick in 1922, when he moved to the University of Vienna. In the discussions of what we now know as the Vienna Circle, however, Schlick's earlier conception of philosophy, as the foundational core, as it were, of all the special sciences, underwent a radical transformation. For one of the first orders of business of the Circle was to assimilate and appropriate the new advances in mathematical logic due to Gottlob Frege and Bertrand Russell, as these advances were philosophically articulated and interpreted by the *Tractatus Logico-Philosophicus* (1922) of the young Ludwig Wittgenstein. But here Schlick and the Circle encountered the following ideas:

The totality of true propositions is the whole of natural science (or the totality of the natural sciences).

Philosophy is not one of the natural sciences.
(The word "philosophy" must mean something that stands above or below the natural sciences, not beside them.)

The aim of philosophy is the logical clarification ofthoughts.
Philosophy is not a doctrine but an activity.
A philosophical work consists essentially of elucidations.
Philosophy does not result in "philosophical propositions," but rather in propositions becoming clear.（此处有原注14：Wittgenstein (1922, §§ 4.111-4.1112)）

A proper understanding of the new mathematical logic shows, according to the *Tractatus*, that the only meaningful propositions - propositions that can be meaningfully said to be true or false - are those of the individual natural sciences. And there can be no "ultimate principles" of these sciences whose articulation and formulation would belong, as its special province, to philosophy. All philosophy can do is analyze the logical form or logical structure of the propositions of the special sciences, whereby it issues in no propositions - no "ultimate principles" - of its own, but simply in the activity of logical clarification itself, an activity that does not involve the formulation or articulation of further meaningful propositions in turn.
